Allow certbot to update certs in HAProxy's config dir
ChameleonCloud/kolla-ansible pull request #33
Opened 2022-10-21 16:48 UTC by super-cooper

The original patch only updated the certs in memory, so restarting
HAProxy would load the old certs.

2022-10-21 16:48 UTC, super-cooper commented
![](https://github.trello.services/images/mini-trello-icon.png) [Automate TLS certificate renewal for CHI-in-a-box sites](https://trello.com/c/nyJl1B03/2795-automate-tls-certificate-renewal-for-chi-in-a-box-sites)

2022-10-21 17:18 UTC, msherman64 reviewed
how does this interact with haproxy's startup behavior if a cert is present in say site-config or /etc/kolla/haproxy?

Will haproxy load the "static one", then a letsenrypt renewal will overwrite it?
Can we make haproxy load the one from the letsencrypt volume on startup, if present, and remove the race?

2022-10-26 16:03 UTC, msherman64 requested changes
we want to avoid writing to the kolla config dir, it is populated from the templates during `genconfig` and `deploy`

can we write the assembled cert into the lettsencrypt volume instead, and have haproxy load it if present? (as was done previously)

2022-10-26 16:03 UTC, msherman64 commented on ansible/roles/letsencrypt/templates/haproxy-reload.sh.j2
> +    echo $full_cert | tee $cert_path /etc/haproxy/haproxy.pem
same issue as above, this writes into a config dir, but will get overwritten when cc-ansible runs.

2022-10-27 15:39 UTC, super-cooper commented
> This would allow Let's Encrypt to manage its own certs, and tell HAProxy to use them, without stomping all over any TLS configuration manually set by the user

This, however, would cause HAProxy to load a bad cert if the container was restarted with `docker restart haproxy` :confounded:

2022-10-28 22:03 UTC, super-cooper commented
Closing this after discussing with Mike in slack

2022-10-28 22:03 UTC, closed without merging